### ISSUE TITLE
Chinese disorderly code

### ISSUE THREAD

**Issue by ejzhang** [dbcli/litecli#54]
![image](https://user-images.githubusercontent.com/452491/52171725-da28d000-279c-11e9-9017-e125081e53e4.png)

**Comment by amjith** [comment]
@ejzhang Can you try setting the following option in the [config](https://litecli.com/config/) file? 

`auto_vertical_output = True`

My suspicion is the width of the output doesn't fit in the screen and it is causing the output to appear garbled. 

When you set that option in the config file, the output will switch to a vertical mode instead of the table mode.

**Comment by ejzhang** [comment]
![image](https://user-images.githubusercontent.com/452491/52384661-6991f400-2ab9-11e9-86d2-36f372aab49a.png)
I try setting the option "auto_vertical_output = True" in the config file, It is unchanged.

**Comment by amjith** [comment]
@tsroten I could use some help here.

**Comment by amjith** [comment]
Can you explain to me what is wrong with the output? 

Perhaps you can post the output from the default client for comparison.

**Comment by tsroten** [comment]
Yeah, just for comparison, I have an English and Chinese in this screenshot. They basically function the same with the regards to wrapping across lines:

![test-litecli](https://user-images.githubusercontent.com/3047055/52389609-e1c8cd00-2a59-11e9-859a-9013ad19dfab.png)

**Comment by amjith** [comment]
Please reopen the issue if you're still having this problem.

**Comment by TheProjectManager** [comment]
intimidating
